"""Setup db.

Revision ID: c19efa6d6351
Revises: 
Create Date: 2025-07-31 11:05:19.838598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19efa6d6351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biddings',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('locks', sa.Integer(), nullable=False, comment='\n            This field help controlling when this bidding has all files processed.\n            The function that matches it with alerts can check: bidding.locks == 0.\n            Meaning, no file of this bidding is being processed.\n        '),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('words', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tokens', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bidding_hash', sa.String(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('tokens', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['bidding_hash'], ['biddings.hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('biddings')
    # ### end Alembic commands ###
